//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoProj.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentInfo
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int RacketId { get; set; }
        public System.DateTime DateRented { get; set; }
        public System.DateTime DateToReturn { get; set; }
    }
}
